backend:
  name: github
  repo: gregorykorte/junctajuvant
  branch: main
  base_url: https://junctajuvant.pages.dev/api/auth    # <- same-origin proxy you just added

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: posts
    label: Posts
    folder: src/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Published at, widget: datetime }
      - { name: excerpt, label: Excerpt }
      - { name: body, label: Body, widget: markdown }

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    format: "markdown"
    fields:
      - { name: title, label: Title }
      - { name: slug, label: URL Slug, hint: "Lowercase, hyphens only (e.g., about-us)" }
      - { name: excerpt, label: Excerpt, required: false }
      - { name: feature_image, label: Feature Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }

